services:
  - type: web
    name: creator-os
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        value: https://creatoros.omeganetwork.co/callback.html
      - key: NODE_ENV
        value: production
